# Введение

In [1]:
print("Hello, HSE student!") #this is my comment

Hello, HSE student!


Конец строки выражения является окончанием инструкции, никаких знаков на конце не требуется, исключением являются вложенные инструкции (инструкция – элемент языка, определяющий действие, которое требуется выполнить).

Комментарии - вспомогательные строки, не обрабатываемые программой, обозначаются знаком # перед началом строки и действуют до конца строки. 

[Про ФКН НИУ ВШЭ](https://cs.hse.ru/)

### Типы данных

In [2]:
#функция type() возвращает тип объекта
type(3) #целое число

int

In [3]:
type("hi") #строка

str

In [4]:
type(True) #логическая переменная

bool

In [5]:
type(3.1088832) #число с плавающей точкой

float

In [6]:
type(None) #неопределенное значение

NoneType

In [7]:
type([3,7,8,4])

list

In [8]:
type((3,7,8,4))

tuple

In [9]:
type({'first':2, 'second': 5, 'third': 12})

dict

### Формула

$$ \sqrt {2/4^7} $$

### Переменные

Говоря о присвоении значения переменной, стоит отметить, что в реальности происходит процесс связывания ссылки на объект с объектом, находящемся в памяти посредством оператора = . Таким образом в инструкции типа var = 12, "var" - ссылка на объект, а "12" - объект целочисленного типа. Каждый раз, когда в тексте будет упоминаться процесс присвоения значения - помните, что в этот момент происходит процесс связывания ссылок с объектами.

In [10]:
a=7
b=4

In [11]:
a**b, a+b, a-b, a*b

(2401, 11, 3, 28)

In [12]:
y=7
z = 2/y

In [13]:
z

0.2857142857142857

In [14]:
type(z)

float

In [15]:
z='HSE'

In [16]:
type(z)

str

In [17]:
#каскадное присваивание 
x=y=z=0
print(x,y,z)

0 0 0


In [18]:
#множественное присваивание 
x, y, z = 1, 2, 3
print(x,y,z)

1 2 3


### Обмен переменных значениями

In [19]:
a = 2
b = 5

In [20]:
#через третью переменную
tmp = a
a = b
b = tmp
print('a =', a, ';', 'b =', b)

a = 5 ; b = 2


In [21]:
#c помощью множественного присваивания
a = 2
b = 5
tmp1, tmp2 = b, a
a, b = tmp1, tmp2 
print('a =', a, ';', 'b =', b)

a = 5 ; b = 2


In [22]:
a = 2
b = 5
a, b = b, a
print('a =', a, ';', 'b =', b)

a = 5 ; b = 2


### Укороченные операторы присваивания

In [23]:
x +=1 #значение возрастает на 1
y -=10 #значение снижается на 10е

### Print

In [24]:
university_name = "HSE"

In [25]:
city_name = "Moscow"

In [26]:
year = 2023

In [27]:
print ("In " + str(year) + " the " + university_name + " is located in " + city_name + ".")

In 2023 the HSE is located in Moscow.


In [28]:
university_name = "MSU"

In [29]:
print ("The " + university_name + " is located in " + city_name + ".")

The MSU is located in Moscow.


### Работа со строками

Строковые выражения могут заключаться в одинарные и двойные кавычки. 

Экранирование с помощью символа \ отменяет действие кавычки, и она воспринимается, как часть текста.

In [30]:
print("Hello\nWorld") #перенос строки

Hello
World


In [31]:
print("Hello, "+" World!") #соединение строк

Hello,  World!


In [32]:
print("Hello\"World") #экранирование

Hello"World


In [36]:
phrase = "HI HSE!"

In [37]:
print(phrase)

HI HSE!


In [38]:
print(phrase.lower()) #изменение регистра

hi hse!


In [39]:
print(phrase.upper()) #изменение регистра

HI HSE!


In [40]:
print(phrase.islower()) #проверка регистра

False


In [41]:
print(phrase.isupper()) #проверка регистра

True


In [42]:
print(len(phrase)) #длина строки

7


In [43]:
print(phrase[3]) #индексация строк

H


In [44]:
print(phrase.index("HSE")) #позиция слова в строке

3


In [45]:
phrase.replace("H", "Z") #заменить символ 

'ZI ZSE!'

### Арифметические операции

In [46]:
3 + 4.5

7.5

In [47]:
3 - 4.5

-1.5

In [48]:
3/1.5 #деление

2.0

In [49]:
2*6 #умножение

12

In [50]:
2**6 # возведение в степень

64

In [51]:
3*4+5

17

In [52]:
3*(4+5)

27

In [53]:
10%7 #остаток от деления

3

In [54]:
10//7 #целая часть от деления

1

In [55]:
num=-120
print(abs(num)) #модуль числа

120


In [56]:
pow(3,4) #возведение в степень

81

In [57]:
max (99,133,44,55) #максимум

133

In [58]:
min(993828,3232,4492) #минимум

3232

In [59]:
round(3.49) #округление

3

In [60]:
round(100/12,3) # round (x, n) округление до n знаков после запятой

8.333

# Импорт модулей

In [66]:
import math # импорт  целого модуля без переименования
math.sqrt(4)

2.0

In [67]:
import math as mt # импорт  целого модуля с переименованием
mt.sqrt(4)


2.0

In [68]:
from math import sqrt # импорт отдельной функции из модуля без переименования
sqrt(4)

2.0

In [69]:
from math import sqrt as s # импорт отдельной функции из модуля с переименованием
s(4)

2.0

In [70]:
from math import * # импорт всех функции из модуля
sqrt(4)

2.0

### Модуль math https://docs.python.org/3/library/math.html

In [71]:
help(math)

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.

        The result is between 0 and pi.

    acosh(x, /)
        Return the inverse hyperbolic cosine of x.

    asin(x, /)
        Return the arc sine (measured in radians) of x.

        The result is between -pi/2 and pi/2.

    asinh(x, /)
        Return the inverse hyperbolic sine of x.

    atan(x, /)
        Return the arc tangent (measured in radians) of x.

        The result is between -pi/2 and pi/2.

    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.

        Unlike atan(y/x), the signs of both x and y are considered.

    atanh(x, /)
        Return the inverse hyperbolic tangent of x.

    cbrt(x, /)
        Return the cube root of x.

    ceil(x, /)
        Return the ceiling of x as an Integral.

        This i

In [73]:
help(sqrt)

Help on built-in function sqrt in module math:

sqrt(x, /)
    Return the square root of x.



In [74]:
math.sqrt(36) #квадратный корень

6.0

In [75]:
math.floor(3.9) # отбрасывает всё после десятичного разделителя

3

In [76]:
math.ceil(3.009) # округляет до ближайшего целого в большую сторону

4

# Список 


Список представляет собой последовательность элементов, пронумерованных от 0. Элементы могут быть разных типов. Список можно задать перечислением элементов списка в квадратных скобках.

In [77]:
faculties = ["Mathematics", "Economic Sciences", "Computer Science", "Humanities", 
             "Social Sciences", "Physics"]

In [78]:
type(faculties)

list

In [79]:
#Можно создать список в списке
['s', 'p', ['is', 7], 2]

['s', 'p', ['is', 7], 2]

### Индексация и срезы

In [80]:
faculties[0] #Первый элемент списка. Нумерация начинается с нуля.

'Mathematics'

In [81]:
faculties[-1] #Последний элемент списка. 

'Physics'

In [82]:
print(faculties)
faculties[1] = "Chemistry" #заменить значение в списке
print(faculties)

['Mathematics', 'Economic Sciences', 'Computer Science', 'Humanities', 'Social Sciences', 'Physics']
['Mathematics', 'Chemistry', 'Computer Science', 'Humanities', 'Social Sciences', 'Physics']


In [83]:
mixedlist = ["HSE", 9, 8.41, True, 7] #смешанный список

In [84]:
mixedlist[0:] #срез

['HSE', 9, 8.41, True, 7]

In [85]:
mixedlist[2:4] #срез

[8.41, True]

In [86]:
mixedlist[:3] #срез

['HSE', 9, 8.41]

### Доступные методы работы со списками

In [87]:
help(faculties)

Help on list object:

class list(object)
 |  list(iterable=(), /)
 |
 |  Built-in mutable sequence.
 |
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |
 |  Methods defined here:
 |
 |  __add__(self, value, /)
 |      Return self+value.
 |
 |  __contains__(self, key, /)
 |      Return bool(key in self).
 |
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __getitem__(self, index, /)
 |      Return self[index].
 |
 |  __gt__(self, value, /)
 |      Return self>value.
 |
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  __it

### Узнать индекс элемента

In [88]:
print(faculties)
faculties.index("Physics")

['Mathematics', 'Chemistry', 'Computer Science', 'Humanities', 'Social Sciences', 'Physics']


5

### Добавить второй список в конец первого

In [89]:
faculties.extend(['Philosophy', 'Management'])
faculties

['Mathematics',
 'Chemistry',
 'Computer Science',
 'Humanities',
 'Social Sciences',
 'Physics',
 'Philosophy',
 'Management']

In [90]:
first_list = [5, 8, 2]
second_list = [1, 9, 4]
new_list = first_list + second_list
new_list

[5, 8, 2, 1, 9, 4]

### Добавить элемент в список

In [91]:
faculties.append("Biology and Biotechnology") #в конец списка
faculties

['Mathematics',
 'Chemistry',
 'Computer Science',
 'Humanities',
 'Social Sciences',
 'Physics',
 'Philosophy',
 'Management',
 'Biology and Biotechnology']

In [92]:
print(faculties)
faculties.insert(1, "Urban and Regional Development") #в середину списка
print(faculties)

['Mathematics', 'Chemistry', 'Computer Science', 'Humanities', 'Social Sciences', 'Physics', 'Philosophy', 'Management', 'Biology and Biotechnology']
['Mathematics', 'Urban and Regional Development', 'Chemistry', 'Computer Science', 'Humanities', 'Social Sciences', 'Physics', 'Philosophy', 'Management', 'Biology and Biotechnology']


### Удалить элемент из списка

In [93]:
print(faculties)
del(faculties[1:3]) #удалить 2 и 3 элементы
print(faculties)

['Mathematics', 'Urban and Regional Development', 'Chemistry', 'Computer Science', 'Humanities', 'Social Sciences', 'Physics', 'Philosophy', 'Management', 'Biology and Biotechnology']
['Mathematics', 'Computer Science', 'Humanities', 'Social Sciences', 'Physics', 'Philosophy', 'Management', 'Biology and Biotechnology']


In [94]:
print(faculties)
faculties.pop(3) #удалить элемент с индексом 3
print(faculties)

['Mathematics', 'Computer Science', 'Humanities', 'Social Sciences', 'Physics', 'Philosophy', 'Management', 'Biology and Biotechnology']
['Mathematics', 'Computer Science', 'Humanities', 'Physics', 'Philosophy', 'Management', 'Biology and Biotechnology']


In [95]:
faculties.remove("Computer Science") #удалить конкретный элемент
faculties

['Mathematics',
 'Humanities',
 'Physics',
 'Philosophy',
 'Management',
 'Biology and Biotechnology']

### Отсортировать список

In [96]:
faculties

['Mathematics',
 'Humanities',
 'Physics',
 'Philosophy',
 'Management',
 'Biology and Biotechnology']

In [97]:
faculties.sort()
faculties

['Biology and Biotechnology',
 'Humanities',
 'Management',
 'Mathematics',
 'Philosophy',
 'Physics']

In [98]:
faculties.sort(reverse = True) #поменять порядок сортировки
faculties

['Physics',
 'Philosophy',
 'Mathematics',
 'Management',
 'Humanities',
 'Biology and Biotechnology']

### Скопировать список

In [99]:
faculties2 = faculties.copy()
faculties2 

['Physics',
 'Philosophy',
 'Mathematics',
 'Management',
 'Humanities',
 'Biology and Biotechnology']

### Очистить список

In [100]:
faculties.clear()
faculties

[]

# Кортеж

In [101]:
mytuple = (4, 5, 12, 8, 4)
mytuple

(4, 5, 12, 8, 4)

In [102]:
mytuple[1] #можно обратиться к элементу по индексу

5

In [103]:
mytuple[1] = 7 # нельзя изменить

TypeError: 'tuple' object does not support item assignment

In [104]:
mytuples = [(4,3), (5,2), (6,7)] #кортежи как элементы списка

# Словарь

Тип данных, в котором элементы нумеруются не натуральными числами, а произвольными объектами. Каждая запись в словаре состоит из двух частей: ключ (до двоеточия) и значение (после двоеточия).

Поскольку словари являются неупорядоченными коллекциями, то к ним не применяется понятие индекса элемента и не применяется операция извлечения среза.

In [105]:
population = {"Russia": 144, "USA": 328, "UK":67, "Canada": 38}
population

{'Russia': 144, 'USA': 328, 'UK': 67, 'Canada': 38}

In [106]:
population["Russia"]

144

In [107]:
population['Russia'] = 145 # изменение значения
population

{'Russia': 145, 'USA': 328, 'UK': 67, 'Canada': 38}

In [108]:
population['Germany'] = 83 # добавление новой записи
population

{'Russia': 145, 'USA': 328, 'UK': 67, 'Canada': 38, 'Germany': 83}

In [109]:
population.keys() # список всех ключей словаря

dict_keys(['Russia', 'USA', 'UK', 'Canada', 'Germany'])

In [110]:
population.values() # список всех значений без ключей

dict_values([145, 328, 67, 38, 83])

In [111]:
# ключами словарей могут быть не только строчки, но и числа
squares={1:1, 2:4, 3:9}
print(squares)

{1: 1, 2: 4, 3: 9}


# Цикл for

Часто используется, чтобы пройти по любому итерируемому объекту, будь то списки, словари, кортежи, строки и не требует ручного увеличения счетчика итераций. Для генерации последовательности чисел используется range ().

In [112]:
my_numbers = [8.7, 12, 6, 13.4, 89]
for number in my_numbers:
    print(number + 3)
    print("Let's go to next number")
print("That's all")

11.7
Let's go to next number
15
Let's go to next number
9
Let's go to next number
16.4
Let's go to next number
92
Let's go to next number
That's all


# Функция range

Для повторения цикла некоторое заданное число раз можно использовать цикл for вместе с функцией range.

In [113]:
for i in range(5):
    print("Hello!")
    print("i =", i)

Hello!
i = 0
Hello!
i = 1
Hello!
i = 2
Hello!
i = 3
Hello!
i = 4


In [114]:
list(range(5))

[0, 1, 2, 3, 4]

In [115]:
list(range(4, 18, 3))

[4, 7, 10, 13, 16]

In [116]:
list(range(12, 4, -1))

[12, 11, 10, 9, 8, 7, 6, 5]

### Оператор continue

Оператор continue позволяет начать следующий проход цикла, минуя оставшиеся инструкции.

In [117]:
for var in 'Python':
    if var == 'h':
        continue
    print(var)

P
y
t
o
n


### Оператор break

Оператор break досрочно прерывает цикл.



In [118]:
for var in 'Python':
    if var == 'h':
        break
    print(var)

P
y
t


### for…break…else

Оператор else проверяет цикл на экстренный выход (break). Если экстренного выхода не было, т.е. оператор break не был выполнен, блок инструкций вложенный в оператор else - выполняется.


In [119]:
for var in 'Python':
    if var == 'a':
        break
    print(var)
else: print('Символа a нет в слове Python') 

P
y
t
h
o
n
Символа a нет в слове Python


In [121]:
for var in 'Pythonabc':
    if var == 'a':
        break 
    print(var) 
else: print('Символа a нет в слове Python') 


P
y
t
h
o
n


Операторы continue, break и else работают с циклами for и while.

# Проверка условий


In [122]:
6<9

True

In [123]:
condition = 3>9
print (condition)

False


In [124]:
type(condition)

bool

In [125]:
a=8
a==7

False

# Условный оператор if

Условные операторы нужны для проверки условий и, в зависимости от результата, чтобы вести логику выполнения программы в нужном направлении.

Условный оператор if ("если") является основным оператором проверки выполнения условия. Для того, чтобы выполнить простую вложенную инструкцию, необходимо проверить условие на соответствие, использовав оператор if.

In [126]:
var = 5 #объявляем переменную
if var < 10: #выполняем проверку условия
    print("var less than 10") #если условие выполняется, то выполняется и вложенная инструкция    

var less than 10


Оператор if позволяет выполнить вложенную инструкцию, если результат выражения True, а что, если нам необходимо, чтобы программа могла выполнять действия и в случае False результата? Для этого мы можем использовать оператор else. Условный оператор else ("иначе") является продолжением основной инструкции. 

In [127]:
var_1 = 10  
var_2 = 9 #объявляем переменные
if var_1 == var_2:# выполняем проверку условия
    print("var_1 equal var_2") #если True
else:# здесь не надо писать условие
    print("var_1 not equal var_2") #выполняется другая вложенная инструкция  

var_1 not equal var_2


Если для решения задачи нас интересует более двух возможных ситуации, то предусмотрен оператор elif (сокращение от конструкции else if), который позволяет добавить дополнительные условия в логику выполнения программы.

Количество конструкций elif может быть множество, тогда, как if и else используются по 1 разу в рамках одной инструкции.

In [128]:
is_male = False
is_tall = False

In [129]:
if is_male and is_tall:
    print("You are a tall male")
elif is_male and not(is_tall):
    print("You are a short male")
elif not(is_male) and is_tall:
    print("You are a tall female")
else:
    print("You are not a male and not tall")

You are not a male and not tall


In [130]:
num1, num2, num3 = 9,33,8
if num1 >= num2 and num1>=num3: 
    print (num1)
elif num2 >= num1 and num2>=num3:
    print (num2)
else:
    print (num3)   

33


In [131]:
a = int(input("Пожалуйста, введите число от 0 до 100: "))
if a <= 100:
    if a >= 0:
        print("Спасибо, мне нравится ваше число")
    else:
        print("Вы ошиблись, это не число от 0 до 100")
else:
    print("Вы ошиблись, это не число от 0 до 100")

Пожалуйста, введите число от 0 до 100:  8


Спасибо, мне нравится ваше число


# Цикл while

Мы использовали цикл for, чтобы перебрать элементы  списка или выполнить некоторую операцию какое-то конечное число раз. Цикл while нужен, если мы хотим выполнять что-то до тех пор, пока выполняется некоторое условие.

In [132]:
i = 1
while i <= 10: # specify a loop condition
    print(i)
    i = i + 1 # или i += 1

print("Done")

1
2
3
4
5
6
7
8
9
10
Done


In [133]:
secret_word = "hse"
guess = ""

while guess != secret_word:
    guess = input("Enter guess: ")
print("You win!")

Enter guess:  kl
Enter guess:  khh
Enter guess:  hse


You win!


In [135]:
#вложенные циклы
x = int(input())
while x > 0: 
    y=x
    while y > 0:
        y -=1
        print (y)
    x-=1
    print("stop")

 8


7
6
5
4
3
2
1
0
stop
6
5
4
3
2
1
0
stop
5
4
3
2
1
0
stop
4
3
2
1
0
stop
3
2
1
0
stop
2
1
0
stop
1
0
stop
0
stop


# Функция

Представляет собой фрагмент кода, который решает определенную задачу. У функции есть имя и список аргументов, которые она принимает.

Важно документировать описание к любой функции, чтобы каждый раз не разбирать написанное заново. Для этого используют строки, заключенные в тройные кавычки. Поскольку описание функции зачастую состоит более, чем из 1 строки, использование строк с тройными кавычками очень удобно. Обычно под документирование выделяют место между определением функции и началом основного кода.


In [136]:
# Программа для вычисления факториала какого-нибудь числа.
n = 7

f = 1
for i in range(2, n+1):
    f = f * i
    # эквивалентный синтаксис: f *= i
print(f)


5040


In [137]:
# функция, вычисляющая факториал
def factorial(n):
    """
    Эта функция
    рассчитает факториал
    не забудьте задать параметр
    """ 
    f = 1
    for i in range(2, n+1):
        f = f * i
    return f
print(factorial(2))
print(factorial(4))
print(factorial(12))

2
24
479001600


In [ ]:
factorial() #нажмите Shift+Tab

In [139]:
# Функция вычисляет модуль числа
def f_abs(x): 
    if x > 0:
        return x
    else:
        return -x
print(f_abs(8))
print(f_abs(0))
print(f_abs(-6))

8
0
6


### return

Инструкция return позволяет вернуть значение, которое нам необходимо. Это необходимо для того, чтобы получить определенный результат и затем дальше использовать его в программе.

Функция может быть любой сложности, внутри конструкции def -> return, мы можем написать любой код. Смысл в функциях заключается в том, чтобы не писать один и тот же код повторно, а просто, в нужный момент, вызывать заранее написанную функцию. Также функция может быть без параметров или может не возвращать какое-то конкретное значение или не заканчиваться инструкцией return. Код под инструкцией def будет относиться к функции до тех пор, пока он вложен в эту инструкцию, то есть отступает от def.


In [140]:
def hello(name):
    return "Hello, "+name+"!" # возвращает строку
s = hello("World")
print(s)

Hello, World!


In [141]:
def say_hello(name):
    print("Hello, "+name+"!") # не возвращает строку, просто выводит её
s = say_hello("HSE")
print(s)

Hello, HSE!
None


In [142]:
# Передача аргументов функции
def hello(name, surname):
    print("Hello,", name, surname)

hello("Alex", "Petrov")

Hello, Alex Petrov


In [143]:
def hello(name, surname = "Nosurname"): 
# Если значение параметра не указано, то берётся значение по умолчанию.
    print("Hello,", name, surname)

hello("Alex", "Petrov")
hello("Alex")

Hello, Alex Petrov
Hello, Alex Nosurname


In [144]:
hello(surname = "Ivanov", name = "Vasya") 
# если указывать имена аргументов, то их порядок не важен

Hello, Vasya Ivanov


In [145]:
# функция с неограниченным числом аргументов
def my_print(*args):
    for x in args:
        print(x)
        
my_print(6, 8.7, 9, 'hello', 99, 551)

6
8.7
9
hello
99
551


# Библиотека numpy

Ускоряет и упрощает работу с числами. Главный объект, с которым мы будем работать — это np.array. Практически все операции для массива выполняются поэлементно.

In [146]:
numbers = [1.2] * 10000
print(numbers)

[1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2,

In [147]:
import numpy as np
np_numbers = np.array(numbers) # преобразуем список в массив
# np.array — это специальный тип данных, похожий на список, но содержащий данные только одного типа
np_numbers

array([1.2, 1.2, 1.2, ..., 1.2, 1.2, 1.2])

In [148]:
type(np_numbers)

numpy.ndarray

In [149]:
np_numbers[3] 

1.2

In [150]:
len(np_numbers)

10000

In [151]:
np_squares = np_numbers**2
np_squares

array([1.44, 1.44, 1.44, ..., 1.44, 1.44, 1.44])

In [152]:
q = np.array([4, 5, 8, 9])
print(q[0])
print(q[2])
# можно обращаться к элементам массива по индексам, как и к спискам

4
8


In [153]:
q[0] = 12 #меняются элементы также
q

array([12,  5,  8,  9])

In [154]:
q[1:3] #можно делать срезы

array([5, 8])

In [155]:
q = np.array([4, 5, 8, 9])
w = np.array([2, 3, 6, 10])
q + w
#арифметические операции над массивами выполняются поэлементно

array([ 6,  8, 14, 19])

In [156]:
np.concatenate( [q, w] )
# для конкатенации

array([ 4,  5,  8,  9,  2,  3,  6, 10])

In [157]:
q*w #перемножение элементов

array([ 8, 15, 48, 90])

In [158]:
q = np.array([14, 8, 14, 9])
w = np.array([1, 3, 4])
q + w # если у массивов разная длина, то ничего не получится

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [159]:
x = np.array([1,2,3,4,5])
np.sqrt(x) # используем функцию sqrt из numpy

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [160]:
import math
math.sqrt(x) #аналогичная функция из math не работает

TypeError: only length-1 arrays can be converted to Python scalars

In [161]:
x = np.array([1.1, 2.2, 3.3, 4.4, 5.5])
y = x[ x < 4 ] # создать новый массив на основе элементов, которые меньше 4
y

array([1.1, 2.2, 3.3])